
services:

  postgres: 
    image: postgres
    restart : always

    environment:
      POSTGRES_USER: transitpost
      POSTGRES_PASSWORD: transitpost
      POSTGRES_DB: transitpost
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data:


# 172.26.64.1