version: "3.9"

services:
  web:
    container_name: web
    build: .
    ports:
    - "8000:8000"
    environment:
      - DB_URL="postgresql://transitpost:transitpost@postgres:5432/transitpost"
    
    volumes:
      - ./app:/code/app
      - ./static:/code/static
      - ./templates:/code/templates

    
    depends_on:
      - pgadmin

  postgres: 
    image: postgres
    restart : always

    environment:
      POSTGRES_USER: transitpost
      POSTGRES_PASSWORD: transitpost
      POSTGRES_DB: transitpost
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  pgdata: {}


# 172.26.64.1