version: '3.9'

services:
  web:
    build: .
    ports:
    - "8000:8000"
    
    volumes:
      -./app:/app
      -./static:/app/static
      -./templates:app/templates
  db: 
    image: postgres
    restart : unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER: transitadmin
      - POSTGRES_PASSWORD: gtfsuser0000
      - POSTGRES_DB: DB
    ports:
      -'5432:5432'
    # volumes:
    #   - ./db:/var/lib/postgresql/data
    #   - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql


#     depends_on:
#       - postgres
#     environment:
#       DB_HOST: db
#       DB_NAME: gtfs_del
#       DB_USER: transitadmin
#       DB_PASS: gtfsuser0000
    
#     entrypoint: /entrypoint.sh
  
#   postgres:
#     image: postgres:14-alpine
#     volumes:
#       - ~/apps/postgres: /var/lib/postgresql/data
#     restart: always
#     environment:
#       POSTGRES_DB : gtfs_del
#       POSTGRES_USER : transitadmin
#       POSTGRES_PASSWORD : gtfsuser0000


# volumes:
#   pgdata:

# 172.26.64.1